### ISSUE TITLE
PR: better project description

### ISSUE THREAD

**Issue by ai** [animakit/animakit-core#2]
We need good project description. This description should be very short, like 1-2 sentences. It should show what is project and what is main feature of project.

Right now we have “React components developed to make your site more friendly ;)” on [homepage](http://askd.github.io/animakit). It is a good start, but we should make it better. Right now, main problem us that description doesn’t show how website will be friendly exactly. For example, icons packs make website friendly too ;).

What do you think about: “Animations library for React. Just wrap your exists UI with Animakit components to get transitions for better UX.”?

**Comment by askd** [comment]
I liked the description and used the second sentence. Thank you!

**Comment by ai** [comment]
Awesome! :)
