### ISSUE TITLE
PR: Usage section in homepage

### ISSUE THREAD

**Issue by ai** [animakit/animakit-core#3]
If we made homepage as landing page, we need to implement ll landing pages features:
1. What is this project about (#2)
2. Code examples (already done)
3. How it differs from other projects (need to finish)
4. Call to action — how to implement it in my project (**we need to add it**)

**Comment by ai** [comment]
Usage could contain this steps:
1. Install necessary components by npm.
2. Import component to JS.
3. Wrap some code inside your React components.

Yeap, users need this step. But also this steps will explain how simple Animakit usage is. Also it will show, that you could install only necessary components (we do it in FAQ right now, but code example is always better than text).

**Comment by ai** [comment]
Also I think we need same Usage section on every component page

**Comment by askd** [comment]
I liked the idea with 3 steps and added the section "Easy to use" on the homepage. But I haven't yet figured out how to do the CTA.

**Comment by ai** [comment]
What is CTA?

**Comment by askd** [comment]
CTA === Call To Action

**Comment by ai** [comment]
I think animations “Learn More” is CTA :D
