### ISSUE TITLE
PR: examples on index

### ISSUE THREAD

**Issue by ai** [animakit/animakit-core#4]
Right now we have no code examples on [askd.github.io/animakit/](http://askd.github.io/animakit/) you need to click on components link to see more.

Unfortunately, most of users have no time to click and find. They want answers right now (remember your-self when you have no time).

I think we should place 1 simpler example on index page and other examples will be on component subpages.

**Comment by askd** [comment]
What do you think about dynamic examples with the slide button? https://animakit.github.io/

**Comment by ai** [comment]
Awesome! Good text.

Maybe we should put “The reason to use” section after animation list section. “The reason to use” is important, but animation is more important.

**Comment by ai** [comment]
Good for first step — close.

But I think we could do better #9
