### ISSUE TITLE
PR: Better animation example

### ISSUE THREAD

**Issue by ai** [animakit/animakit-core#9]
I like first examples on animation pages — they show real examples of animation usage. I think we should add them in animations examples on homepage index, because they will show where this project will be useful (main question for new users)

Also we could remove abstract example:

``` jsx
<AnimakitComponent>
  <YourContent />
</AnimakitComponent>
```

Real example is always better, than abstract.

**Comment by askd** [comment]
I used one abstract example to make step description shorter. There are 3 components now (and there will be more!) so which of real examples to choose?
But if I'm anyway going to replace animations with more real, I'll add more real code snippets separately.

**Comment by ai** [comment]
Making docs shorter — good point :). But I think we should try to find compromise here. There is no sense in short docs, if they didn’t answer on main users questions ;).

On every animation page you have very good example on top (the first example). They are simple, but show real usage cases. I like them. We could use them on index too.

Each, page will be bigger (especially in future). But you know, good landings could be 3-5 screens height. It is OK :).

**Comment by askd** [comment]
I added first component demos on the homepage.
